Support $XDG_CONFIG_HOME in module search path

diff --git a/tests/shtest b/tests/shtest
--- a/tests/shtest
+++ b/tests/shtest
@@ -375,6 +375,42 @@ if ! HOME="$mods/home2" $VALGRIND $Q $JQ -n 'include "g"; empty'; then
     exit 1
 fi
 
+# Test handling of $XDG_CONFIG_HOME.
+
+## If $XDG_CONFIG_HOME is set, load module from $XDG_CONFIG_HOME/jq/
+if [ "$(HOME=/nonexistent XDG_CONFIG_HOME="$mods/xdg1" $VALGRIND $Q $JQ -nr 'include "xdg"; test')" != "foo" ]; then
+    echo "Failed to load module from \$XDG_CONFIG_HOME/jq/" 1>&2
+    exit 1
+fi
+## ~/.jq/ should be searched before $XDG_CONFIG_HOME/jq/
+if [ "$(HOME="$mods/home3" XDG_CONFIG_HOME="$mods/xdg2" $VALGRIND $Q $JQ -nr 'include "priority_test"; test')" != "qux" ]; then
+    echo "~/.jq/ should take priority over \$XDG_CONFIG_HOME/jq/" 1>&2
+    exit 1
+fi
+if $msys || $mingw; then
+    ## If $XDG_CONFIG_HOME is unset, do not fallback to $HOME/.config/jq/
+    if unset XDG_CONFIG_HOME; HOME="$mods/home3" $VALGRIND $Q $JQ -nr 'include "cfg"; test' 2>/dev/null; then
+        echo "Windows should not fallback to \$HOME/.config/jq/ when \$XDG_CONFIG_HOME is unset" 1>&2
+        exit 1
+    fi
+    ## If $XDG_CONFIG_HOME is an empty string, do not fallback to $HOME/.config/jq/
+    if XDG_CONFIG_HOME="" HOME="$mods/home3" $VALGRIND $Q $JQ -nr 'include "cfg"; test' 2>/dev/null; then
+        echo "Windows should not fallback to \$HOME/.config/jq/ when \$XDG_CONFIG_HOME is empty" 1>&2
+        exit 1
+    fi
+else
+    ## If $XDG_CONFIG_HOME is unset, fallback to $HOME/.config/jq/
+    if [ "$(unset XDG_CONFIG_HOME; HOME="$mods/home3" $VALGRIND $Q $JQ -nr 'include "cfg"; test')" != "bar" ]; then
+        echo "Failed to fallback to \$HOME/.config/jq/ when \$XDG_CONFIG_HOME is unset" 1>&2
+        exit 1
+    fi
+    ## If $XDG_CONFIG_HOME is an empty string, fallback to $HOME/.config/jq/
+    if [ "$(XDG_CONFIG_HOME="" HOME="$mods/home3" $VALGRIND $Q $JQ -nr 'include "cfg"; test')" != "bar" ]; then
+        echo "Failed to fallback to \$HOME/.config/jq/ when \$XDG_CONFIG_HOME is empty" 1>&2
+        exit 1
+    fi
+fi
+
 cd "$JQBASEDIR" # so that relative library paths are guaranteed correct
 if ! $VALGRIND $Q $JQ -L ./tests/modules -ne 'import "test_bind_order" as check; check::check==true'; then
     echo "Issue #817 regression?" 1>&2
